### ISSUE TITLE
flexi logger error

### ISSUE THREAD

**Issue by ozkanpakdil** [deinstapel/cursive-flexi-logger-view#12]
After I start the application I got the error below and how it looks in the app

mintozzy@laptop:~/tmp/storytel-tui$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.50s
     Running `target/debug/storytel-tui`
[flexi_logger][ERRCODE::Time] flexi_logger has to work with UTC rather than with local time, caused by IndeterminateOffset
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#time
[flexi_logger][ERRCODE::Write] writing log line failed, caused by Custom { kind: BrokenPipe, error: "cursive callback sink is closed!" }
    See https://docs.rs/flexi_logger/latest/flexi_logger/error_info/index.html#write

![image](https://user-images.githubusercontent.com/604405/213914652-e6cc5966-3091-402a-941a-00012c18dda0.png)

```toml
[dependencies]
reqwest = { version = "0.11.11", features = ["json", "blocking"] }
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
mpv = "0.2.3"
openssl = { version = "0.10.41" }
cursive = { version = "0.18" , default-features = false, features = ["crossterm-backend"]}
cursive-flexi-logger-view = "^0"
flexi_logger = "0.22.6"
```
I used the example code https://docs.rs/cursive-flexi-logger-view/latest/cursive_flexi_logger_view/#using-the-flexiloggerview 

what can be the reason ?

feel free to check https://stackoverflow.com/questions/75200289/cursive-flexi-logger-view-throwing-unhandled-error too.

Thanks
